#define PACKAGE_VERSION "1.39.1"
//#define WITH_UDEV
#define RMNET_SUPPORT_ENABLED
#define MM_RUNTIME_CHECK_ENABLED
//#define QMI_USERNAME ""
//#define QMI_USERNAME_ENABLED
//#define QMI_GROUPNAME ""
//#define QMI_GROUPNAME_ENABLED
// TODO: #define MBIM_QMUX_ENABLED
#define QMI_QRTR_SUPPORTED 1
